# Translations and transliterations --------------------------------------------

# convert greek to latin-ascii
greek2latin <- function(x) {
  sapply(x, function(str) {
    str <- stringi::stri_trans_general(str, "Latin")
    str <- stringi::stri_trans_general(str, "latin-ascii")
    str
  })
}

# translitarate all the columns of a dataframe
trasnlit_all <- function(result) {
  for (cnames in names(result)) {
    result[cnames] <- greek2latin(result[cnames])
  }
  result
}

# tranlate owners to englisn
map_owners <- function(x) {
x <- stringr::str_replace_all(" ", "", x)
  switch (x,
          "DEMOSIAEPICHEIRISEELEKTRISMOU" = "public_power_corp",
          "ETHNIKEMETEOROLOGIKEYPERESIA"  = "natio_meteo_service",
          "ETHNIKOASTEROSKOPEIOATHENAS"   = "natio_observ_athens",
          "ETHNIKOIDRYMAAGROTIKESEREUNAS" = "natio_argic_resear",
          "MOUSEIOPHYSIKESISTORIASKRETES" = "crete_natural_museum",
          "NOMARCHIAKEAUTODIOIKESE"       = "greek_perfectures"  ,
          "POLYTECHNEIOKRETES"            = "crete_eng_faculty",
          "YPOURGEIOAGROTIKESANAPTYXESKAITROPHIMON" = "min_agricult",
          "YPOURGEIOPERIBALLONTOS,ENERGEIASKAIKLIMATIKESALLAGES" = "min_envir",
          x)
}

# translate variables to english
map_variables <- function(x){
  "PH,
  AGNOSTO,
  AGOGIMOTETA,
  AKTINOBOLIA,
  AMMONIA,
  ANEMOS (BEAUF),
  ANEMOS (DIEUTHYNSE),
  ANEMOS (PARELTHON),
  ANEMOS (TACHYTETA),
  ANEMOS (TACHYTETA MESE),
  ANTHRAKAS,
  ARGILIO,
  ARGILOS,
  ARSENIKO,
  ASBESTIO,
  BATHOS YGROU (CHIONOBROCHOMETRO),
  BROCHOPTOSE,
  BROCHOPTOSE (DIARKEIA),
  DIOXEIDIO ANTHRAKA,
  DIOXEIDIO PYRITIOU,
  DOKIMASTIKE ANTLESE,
  DYNAMIKO OXEIDOANAGOGES,
  EXATMISE (DIAPHORA COLORADO),
  EXATMISE (DIAPHORA PICHE),
  EXATMISE (EKTIMEMENE),
  EXATMISE (PARELTHOUSA),
  EXATMISE (PAROUSA),
  EXATMISODIAPNOE,
  ELIOPHANEIA (DIARKEIA),
  THEIIKA,
  THERMOKRASIA (AERA),
  THERMOKRASIA (BAROMETROU),
  THERMOKRASIA (DIAPHORA YGROU-XEROU),
  THERMOKRASIA (EDAPHOUS),
  THERMOKRASIA (EDAPHOUS BATHOS1),
  THERMOKRASIA (EDAPHOUS BATHOS2),
  THERMOKRASIA (EDAPHOUS BATHOS3),
  THERMOKRASIA (EDAPHOUS BATHOS4),
  THERMOKRASIA (EDAPHOUS BATHOS5),
  THERMOKRASIA (EDAPHOUS EL.),
  THERMOKRASIA (EDAPHOUS KALYMENO),
  THERMOKRASIA (EDAPHOUS KALYMENO EL.),
  THERMOKRASIA (EDAPHOUS KALYMENO MEG.)
  THERMOKRASIA (EDAPHOUS MEG.)
  THERMOKRASIA (ELACHISTE)
  THERMOKRASIA (MEGISTE)
  THERMOKRASIA (NEROU)
  THERMOKRASIA (XEROU)
  THERMOKRASIA (YGROU)
  ICHNE YETOU
  KADMIO
  KAIROS
  KALIO
  KATASTASE EDAPHOUS
  KATASTASE THALASSAS
  MANGANIO
  MAGNESIO
  MOLYBDOS
  MONOXEIDIO ANTHRAKA
  NATRIO
  NEPHOKALYPSE
  NEPHOSE
  NEPHOSE (AXIOSEMEIOTA NEPHE)
  NEPHOSE (NE NEPHE)
  NIKELIO
  NITRIKA
  NITRODE
  XERO YPOLOIPO
  ORATOTETA (THALASSA)
  ORATOTETA (STERIA)
  PAROCHE
  PIESE (ATMOSPHAIRIKE)
  PIESE (BAROMETRO STATHERA)
  PIESE (STATHERA BAROM.)
  PIESE (STATHME THALASSES)
  SEMEIAKE STATHME
  SEMEIO DROSOU
  SIDEROS
  SKLEROTETA
  STATHME
  STATHME (PLEMMYRA)
  STEREO PAROCHE
  STEREO-YDROMETRESE
  TASE YDRATMON
  YGRASIA (APOLYTE)
  YGRASIA (SCHETIKE)
  YDRARGYROS
  YDROTHEIO
  YDROMETRESE
  YPSOMETRO
  PHTHORIO
  PHOSPHORIKA
  CHALKOS
  CHIONI
  CHIONI (ATHROISTIKO)
  CHIONI - BROCHE (CHIONOBROCHOMETRO)
  CHIONI (ISODYNAMO YPSOS)
  CHLORIO
  CHROMIO
  PSEUDARGYROS
  PSYCHROMETRO (XERO)
  PSYCHROMETRO (YGRO)"
}
